### ISSUE TITLE
sqlalchemy 2.0.0 breaks pyiron

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_base#1006]
```
Traceback (most recent call last):
  File "/home/janssen/pyiron/projects/2023-01-29-sqs-elastic/run_elastic.py", line 3, in <module>
    import pyiron_gpl
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_gpl/__init__.py", line 4, in <module>
    from pyiron_atomistics.project import Project
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_atomistics/__init__.py", line 4, in <module>
    from pyiron_atomistics.project import Project
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_atomistics/project.py", line 12, in <module>
    from pyiron_base import (
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_base/__init__.py", line 5, in <module>
    from pyiron_base.state import state
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_base/state/__init__.py", line 18, in <module>
    from pyiron_base.database.manager import database as _database
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_base/database/manager.py", line 248, in <module>
    database = DatabaseManager()
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_base/interfaces/singleton.py", line 35, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_base/database/manager.py", line 32, in __init__
    self.open_connection()
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_base/database/manager.py", line 125, in open_connection
    self._database = DatabaseAccess(
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_base/database/generic.py", line 453, in __init__
    retry(
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_base/utils/error.py", line 145, in retry
    return func()
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_base/database/generic.py", line 448, in _create_table
    self.__reload_db()
  File "/home/janssen/miniforge3/lib/python3.9/site-packages/pyiron_base/database/generic.py", line 609, in __reload_db
    self.metadata = MetaData(bind=self._engine)
TypeError: __init__() got an unexpected keyword argument 'bind'
```

**Comment by pmrv** [comment]
So, I feel this is one of the reasons we should reconsider our policy wrt dependency versions.  If we had at least specified 1<=sqlalchemy<2, i.e. the same major version, this would not have happened and saved a lot of work.  Is there some tooling where we can a) receive major bumps from dependabot less often than minor bumps and b) keep the versions in the conda feedstock in sync?

**Comment by jan-janssen** [comment]
Even `pandas` has broken functionality because of the `sqlalchemy` update and we are currently waiting for them to fix this and then once a new version of `mendeleev` is released which then hopefully allows us the upgrade `pyiron_atomistics`. https://github.com/pyiron/pyiron_atomistics/pull/949 .
