### ISSUE TITLE
Coverage run fails

### ISSUE THREAD

**Issue by niklassiemer** [pyiron/pyiron_base#139]
The coverage check currently fails with 
```
Submitting coverage to coveralls.io...
Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
resubmitting with id None-8623016246307919638
Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/coveralls/api.py", line 252, in wear
    response.raise_for_status()
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/coveralls/cli.py", line 85, in main
    result = coverallz.wear()
  File "/usr/share/miniconda/envs/test/lib/python3.9/site-packages/coveralls/api.py", line 255, in wear
    raise CoverallsException('Could not submit coverage: {}'.format(e))
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
Error: Process completed with exit code 1.
```
Is this a temporary problem or what do we have to repair?

**Comment by jan-janssen** [comment]
I assume it is somehow related to the GitHub tokens, I am going to take a look at this on the weekend.

**Comment by jan-janssen** [comment]
Now the coverage token is specified in a file to make it more explicit.

**Comment by niklassiemer** [comment]
Thanks a lot, I will tag the version, once the tests are fine.
