### ISSUE TITLE
HDF5 file not correctly closed 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_base#402]
There is currently an issue with submitting jobs on a shared file system. A simple test setup: 
* Create a job on your own system
* Login to your system via ssh using pysqa and execute the job
* The calculation fails as the HDF5 file remains open after submission

```
/Software/anaconda3/envs/pyiron_test/lib/python3.9/site-packages/pysqa/utils/remote.py:238: UserWarning: Traceback (most recent call last):
  File "/isi/programs/anaconda/anaconda3/envs/pyiron_test/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/isi/programs/anaconda/anaconda3/envs/pyiron_test/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/isi/programs/anaconda/anaconda3/envs/pyiron_test/lib/python3.9/site-packages/pyiron_base/cli/__main__.py", line 2, in <module>
    main()
  File "/isi/programs/anaconda/anaconda3/envs/pyiron_test/lib/python3.9/site-packages/pyiron_base/cli/__init__.py", line 61, in main
    args.cli(args)
  File "/isi/programs/anaconda/anaconda3/envs/pyiron_test/lib/python3.9/site-packages/pyiron_base/cli/wrapper.py", line 34, in main
    job_wrapper_function(
  File "/isi/programs/anaconda/anaconda3/envs/pyiron_test/lib/python3.9/site-packages/pyiron_base/job/wrapper.py", line 139, in job_wrapper_function
    job = JobWrapper(
  File "/isi/programs/anaconda/anaconda3/envs/pyiron_test/lib/python3.9/site-packages/pyiron_base/job/wrapper.py", line 65, in __init__
    "status": get_job_status_from_file(
  File "/isi/programs/anaconda/anaconda3/envs/pyiron_test/lib/python3.9/site-packages/pyiron_base/database/filetable.py", line 334, in get_job_status_from_file
    return h5io.read_hdf5(hdf5_file, job_name + '/status')
  File "/isi/programs/anaconda/anaconda3/envs/pyiron_test/lib/python3.9/site-packages/h5io/_h5io.py", line 263, in read_hdf5
    with h5py.File(fname, mode='r') as fid:
  File "/isi/programs/anaconda/anaconda3/envs/pyiron_test/lib/python3.9/site-packages/h5py/_hl/files.py", line 444, in __init__
    fid = make_fid(name, mode, userblock_size,
  File "/isi/programs/anaconda/anaconda3/envs/pyiron_test/lib/python3.9/site-packages/h5py/_hl/files.py", line 199, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 100, in h5py.h5f.open
OSError: Unable to open file (truncated file: eof = 16384, sblock->base_addr = 0, stored_eof = 284121)
```

The required modifications to pysqa to work with a shared filesystem are included in https://github.com/pyiron/pysqa/issues/92

**Comment by jan-janssen** [comment]
I just had the same issue on a new machine. I was able to fix it by adding the following line to my `.bashrc`: 
```
export HDF5_USE_FILE_LOCKING=FALSE
```

**Comment by pmrv** [comment]
Does this not enable silent data loss to read/write without locks?

**Comment by jan-janssen** [comment]
On certain shared file systems it seems to be required https://docs.nersc.gov/development/libraries/hdf5/#using-hdf5-at-nersc
